In [31]:
import pandas as pd

### Carregando dadods

In [32]:
data = pd.read_csv('DATASET_interests.csv')
data.sort_values(by = 'text').head(20)

,date,id_str,user_name,text,time,latitude,longitude
1806,2018-05-07,5.695078e+07,selphie6999,acehardware makawao h,03:39:18,20.838659,-156.341470
2619,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,22:45:16,19.390000,-155.410000
2584,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,23:02:36,19.500000,-155.110000
2623,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 】 isla de hawaii hawaii km utc s...,22:43:57,19.420000,-155.360000
736,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
183,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
921,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
551,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
372,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
4,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
557,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
743,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
188,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
1944,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
3484,2018-05-01,1.918246e+07,Kane007,ahhhhh another beautiful day wai ’ anapanapa p...,06:59:55,20.785800,-155.997000
1890,2018-05-06,2.379071e+09,tiedyehobo,aloa tiedyehob,22:09:05,19.525750,-155.923580
522,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
339,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
892,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
3504,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000

### Verificando **duplicatas**

In [33]:
spams = data[data['text'].duplicated(keep = False)]
spams.sort_values(by = 'text').head(15)

,date,id_str,user_name,text,time,latitude,longitude
921,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
551,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
183,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
736,2018-04-27,2.054922e+08,chowbabylovin,actually flew hawaii could see avengers infini...,09:12:59,19.573034,-155.962196
743,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
372,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
4,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
557,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
1944,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
188,2018-05-06,1.864570e+07,syvideo,adventures covering lava flow hilo hi leilani ...,18:18:05,19.473500,-154.920000
707,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
522,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
155,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
339,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000
3504,2018-05-01,2.379071e+09,tiedyehobo,aloha hawaii sunset kailua kona hawai,05:25:39,19.650000,-155.994000

### Quantos valores duplicados ?

In [34]:
'Total: {}'.format(len(spams))

'Total: 2536'

In [35]:
"""
keep :
    - first : Drop duplicates except for the first occurrence.
    - last :  Drop duplicates except for the last occurrence.
    - False : Drop all duplicates.
"""
data.drop_duplicates(subset = 'text', keep = False, inplace = True)

In [36]:
data.sort_values(by = 'text').head(15)

,date,id_str,user_name,text,time,latitude,longitude
1806,2018-05-07,5.695078e+07,selphie6999,acehardware makawao h,03:39:18,20.838659,-156.341470
2619,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,22:45:16,19.390000,-155.410000
2584,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,23:02:36,19.500000,-155.110000
2623,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 】 isla de hawaii hawaii km utc s...,22:43:57,19.420000,-155.360000
3484,2018-05-01,1.918246e+07,Kane007,ahhhhh another beautiful day wai ’ anapanapa p...,06:59:55,20.785800,-155.997000
1890,2018-05-06,2.379071e+09,tiedyehobo,aloa tiedyehob,22:09:05,19.525750,-155.923580
1296,2018-05-09,3.405839e+08,PineappleClan,aloha hui hou rest paradise papa carl deepest ...,10:42:58,19.590400,-154.976000
1809,2018-05-07,5.695078e+07,selphie6999,american savings bank pukalani h,03:37:49,20.838396,-156.341712
3435,2018-05-01,3.917680e+07,cyulit,ang tunay na pogi kahit walang ngipin pogi pa ...,10:58:27,20.759100,-156.457000
2385,2018-05-05,4.934616e+08,ashleyyyz3,another perfect sunset day paradise,06:54:13,19.476400,-155.923000
1061,2018-05-27,2.803331e+08,espejomx,aunque de hecho pasaron los tres solo que chil...,13:17:12,19.687487,-155.073662
2840,2018-05-04,2.122696e+07,Mr2theP,ayeeeee darrenvegas kev stylemedia itsirez isl...,03:37:56,20.752200,-155.982000
1062,2018-05-27,2.803331e+08,espejomx,ayer predije temblores pasaron dos funci,13:14:27,19.687487,-155.073662
1895,2018-05-06,2.985539e+07,bcliff84,baby brother coming bench four seasons,21:44:52,20.680811,-156.442663
1610,2018-05-08,1.483622e+09,HappyMonkey604,baby first waterslide westin nanea ocean villa,01:07:23,20.942423,-156.691046

In [37]:
'Total: {}'.format(len(data))

'Total: 1102'

### Matando dado na unha

In [39]:
data[data['user_name'].str.contains("tmj")]

,date,id_str,user_name,text,time,latitude,longitude
922,2018-05-29,28625882.0,tmj_mau_retail,hiring click apply longs drugs shift superviso...,01:08:30,20.748457,-156.454065
923,2018-05-29,47498201.0,tmj_mau_cosmo,fun fresh talented ’ team ulta beauty looking ...,01:06:18,20.874692,-156.457379
924,2018-05-29,23539121.0,tmj_mau_sales,make job awesome fit read opening kahului hi s...,01:05:51,20.887585,-156.465776
925,2018-05-29,24384655.0,tmj_mau_mgmt,hiring read latest job opening paraprofessiona...,01:05:38,20.889335,-156.472947
926,2018-05-29,23898066.0,tmj_mau_hrta,recommend anyone job wailea hi ivmwuhmsy hospi...,01:04:48,20.680279,-156.442027
927,2018-05-29,23539364.0,tmj_mau_health,recommend anyone job dialysis pct maui pmodmvp...,00:51:38,20.891111,-156.504722
928,2018-05-29,23542616.0,tmj_mau_nursing,see latest wailuku hi job click apply travel o...,00:49:29,20.891111,-156.504722
929,2018-05-29,71968934.0,tmj_HI_cstsrv,want work starbucks hiring kailuakona hi click...,00:49:08,19.646028,-155.988356
930,2018-05-28,23539121.0,tmj_mau_sales,hiring read latest job opening sales represent...,23:59:21,20.890112,-156.461430
931,2018-05-28,24384655.0,tmj_mau_mgmt,join starbucks team see latest job opening qsg...,23:59:14,20.878333,-156.682500
933,2018-05-28,59911545.0,tmj_hi_retail,hiring click apply retail merchandiser part ti...,23:58:24,20.023056,-155.671667
936,2018-05-28,23542616.0,tmj_mau_nursing,want work bayada hiring lahaina hi click detai...,23:42:10,20.878333,-156.682500
939,2018-05-28,23539121.0,tmj_mau_sales,hiring read latest job opening store counter s...,22:52:57,20.891512,-156.466533
940,2018-05-28,175235622.0,tmj_HI_facmgmt,hiring click apply facility service associate ...,22:52:57,19.645916,-155.985749
941,2018-05-28,47498201.0,tmj_mau_cosmo,bring retail experience ulta beauty currently ...,22:52:45,20.874692,-156.457379
942,2018-05-28,24384655.0,tmj_mau_mgmt,want work enterprise holdings hiring kahului h...,22:52:44,20.889335,-156.472947
943,2018-05-28,28625882.0,tmj_mau_retail,hiring read latest job opening sales associate...,22:52:06,20.878333,-156.682500
945,2018-05-28,23539364.0,tmj_mau_health,recommend anyone job hematology oncology physi...,22:36:04,20.891111,-156.504722
946,2018-05-28,71968934.0,tmj_HI_cstsrv,recommend anyone job shift supervisor store ma...,22:34:33,20.886414,-156.684167
947,2018-05-28,23542616.0,tmj_mau_nursing,know anyone wants cna look job wailuku hi acmf...,22:34:11,20.891111,-156.504722
948,2018-05-28,23898066.0,tmj_mau_hrta,looking work lanaicity hi check job hpllcefv h...,21:46:25,20.869339,-156.906103
949,2018-05-28,59911545.0,tmj_hi_retail,hiring click apply store team member ddtvdyo r...,21:46:25,19.719112,-155.080928
950,2018-05-28,47498201.0,tmj_mau_cosmo,ulta beauty incredible season growth ’ looking...,21:45:58,20.874692,-156.457379
951,2018-05-28,23539364.0,tmj_mau_health,join envision team see latest job opening kzvn...,21:28:07,20.891111,-156.504722
952,2018-05-28,71968934.0,tmj_HI_cstsrv,looking work lahaina hi check job etsjqmobh cu...,21:27:24,20.876877,-156.679813
953,2018-05-28,23542616.0,tmj_mau_nursing,hiring read latest job opening hemodialysis rn...,21:26:47,20.891111,-156.504722
954,2018-05-28,67487139.0,tmj_hi_sales,join lowe team see latest job opening flghrrdg...,21:26:47,19.645916,-155.985749
956,2018-05-28,28625882.0,tmj_mau_retail,fun fresh talented ’ team ulta beauty looking ...,20:30:07,20.874692,-156.457379
957,2018-05-28,59911545.0,tmj_hi_retail,see latest kailuakona hi job click apply custo...,20:29:46,19.645916,-155.985749
958,2018-05-28,23539121.0,tmj_mau_sales,see latest kahului hi job click apply store co...,20:26:37,20.891512,-156.466533
...,...,...,...,...,...,...,...
2542,2018-05-04,23898066.0,tmj_mau_hrta,hiring read latest job opening pool attendant ...,23:55:17,20.680279,-156.442027
2544,2018-05-04,59911545.0,tmj_hi_retail,looking work keaau hi check job vtphqimyga ret...,23:54:57,19.622263,-155.040660
2546,2018-05-04,28625882.0,tmj_mau_retail,see latest lanaicity hi job click apply gift s...,23:54:34,20.869339,-156.906103
2557,2018-05-04,71968934.0,tmj_HI_cstsrv,hiring click apply customer service associate ...,23:38:36,19.520833,-155.922500
2612,2018-05-04,23898066.0,tmj_mau_hrta,join four seasons resorts lana team see latest...,22:49:08,20.869339,-156.906103
2613,2018-05-04,59911545.0,tmj_hi_retail,job might great fit bbqs patio furniture lawn ...,22:48:58,19.645916,-155.985749
2614,2018-05-04,28625882.0,tmj_mau_retail,recommend anyone job front loader customer ser...,22:48:51,20.876126,-156.455479
2632,2018-05-04,71968934.0,tmj_HI_cstsrv,join engageexcel team see latest job opening b...,22:31:32,20.764428,-156.445006
2690,2018-05-04,71968934.0,tmj_HI_cstsrv,want work engageexcel hiring hi click details ...,21:24:20,19.639992,-155.996905
2700,2018-05-04,59911545.0,tmj_hi_retail,join tractor supply company team see latest jo...,20:26:36,19.707094,-155.088487
2721,2018-05-04,59911545.0,tmj_hi_retail,hiring click apply head cashier wnqxjgyn retai...,19:20:39,19.645916,-155.985749
2725,2018-05-04,71968934.0,tmj_HI_cstsrv,recommend anyone job kailuakona hi oumphqvglm ...,19:06:18,19.704963,-155.950541
2743,2018-05-04,71968934.0,tmj_HI_cstsrv,see latest lanaicity hi job click apply host e...,17:58:38,20.869339,-156.906103
2849,2018-05-04,71968934.0,tmj_HI_cstsrv,hiring read latest job opening guest activitie...,02:59:53,20.869339,-156.906103
2858,2018-05-04,59911545.0,tmj_hi_retail,recommend anyone job kailuakona hi sxmaiam ret...,02:06:37,19.704963,-155.950541
2872,2018-05-04,71968934.0,tmj_HI_cstsrv,recommend anyone job lanaicity hi tltchuh cust...,00:45:38,20.869339,-156.906103
2881,2018-05-03,59911545.0,tmj_hi_retail,want work hi view latest opening pcimiaky reta...,23:54:43,19.896766,-155.582782
2900,2018-05-03,71968934.0,tmj_HI_cstsrv,see latest lanaicity hi job click apply reserv...,22:31:23,20.869339,-156.906103
2944,2018-05-03,71968934.0,tmj_HI_cstsrv,hiring read latest job opening steward goavkwx...,20:13:15,20.869339,-156.906103
3069,2018-05-03,71968934.0,tmj_HI_cstsrv,looking work wailea hi check job trbhptkvmo ma...,01:52:31,20.680279,-156.442027
3078,2018-05-03,71968934.0,tmj_HI_cstsrv,hiring read latest job opening banquet manager...,00:45:26,20.869339,-156.906103
3090,2018-05-02,71968934.0,tmj_HI_cstsrv,join engageexcel team see latest job opening s...,23:38:20,20.764428,-156.445006
3106,2018-05-02,71968934.0,tmj_HI_cstsrv,hiring read latest job opening customer servic...,22:31:08,20.889335,-156.472947
3121,2018-05-02,71968934.0,tmj_HI_cstsrv,interested job kahului hi could great fit xxrp...,21:24:04,20.889335,-156.472947
3143,2018-05-02,71968934.0,tmj_HI_cstsrv,job might great fit passenger service agent eu...,19:06:03,19.639994,-155.996926
3149,2018-05-02,71968934.0,tmj_HI_cstsrv,join bayada team see latest job opening ptftyx...,17:58:28,19.707094,-155.088487
3615,2018-04-30,71968934.0,tmj_HI_cstsrv,recommend anyone job kailuakona hi rqqqefbxc c...,02:59:24,19.704963,-155.950541
3622,2018-04-30,71968934.0,tmj_HI_cstsrv,hiring read latest job opening food runner pm ...,00:45:09,20.869339,-156.906103
3625,2018-04-29,71968934.0,tmj_HI_cstsrv,recommend anyone job wailea hi fitemlzl custom...,23:37:57,20.680279,-156.442027
3633,2018-04-29,71968934.0,tmj_HI_cstsrv,hiring read latest job opening host ess ebalmf...,22:30:48,20.680279,-156.442027

In [40]:
data[data['user_name'].str.contains("eq_map")]

,date,id_str,user_name,text,time,latitude,longitude
955,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,20:31:19,19.41,-155.27
967,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,19:12:40,19.41,-155.29
969,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,19:10:01,19.41,-155.29
971,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,16:47:20,19.41,-155.29
972,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,16:43:22,19.41,-155.28
973,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,16:40:39,19.41,-155.29
974,2018-05-28,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,16:24:40,19.40,-155.29
975,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,14:51:40,19.40,-155.29
976,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,14:40:02,19.41,-155.28
977,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,13:29:20,19.40,-155.29
978,2018-05-28,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,12:41:23,19.42,-155.28
979,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,12:41:22,19.39,-155.27
980,2018-05-28,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,12:36:01,19.38,-155.30
981,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,12:36:00,19.40,-155.30
982,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,11:14:00,19.39,-155.28
983,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,09:42:40,19.41,-155.29
984,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,08:47:36,19.40,-155.29
985,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,07:59:15,19.36,-155.27
986,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,07:28:56,19.40,-155.28
987,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,07:20:56,19.39,-155.28
988,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,06:27:57,19.40,-155.30
989,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,03:58:35,19.40,-155.28
1000,2018-05-28,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,02:34:37,19.40,-155.29
1030,2018-05-27,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:46:35,19.41,-155.29
1032,2018-05-27,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:39:56,19.40,-155.28
1041,2018-05-27,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,21:13:36,19.46,-155.35
1052,2018-05-27,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,18:43:15,19.40,-155.29
1053,2018-05-27,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,18:36:36,19.40,-155.29
1055,2018-05-27,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,16:43:35,19.41,-155.29
1064,2018-05-27,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,11:57:16,19.37,-155.26
...,...,...,...,...,...,...,...
2471,2018-05-05,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,03:07:58,19.29,-154.91
2545,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,23:54:36,19.42,-155.31
2584,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,23:02:36,19.50,-155.11
2593,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:57:18,19.40,-155.32
2600,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:54:37,19.25,-155.21
2611,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:49:16,19.31,-155.22
2616,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:46:36,19.39,-155.26
2619,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 mw 】 isla de hawaii hawaii km ut...,22:45:16,19.39,-155.41
2622,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,22:43:58,19.27,-155.23
2623,2018-05-04,2.920049e+09,eq_map_es2,actualizado 【 】 isla de hawaii hawaii km utc s...,22:43:57,19.42,-155.36
2653,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,21:57:58,19.30,-154.94
2659,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,21:50:37,19.37,-155.02
2663,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,21:47:57,19.32,-154.95
2669,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,21:44:38,19.36,-155.02
2676,2018-05-04,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,21:39:17,19.34,-155.03
2809,2018-05-04,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,08:03:36,19.41,-155.28
2933,2018-05-03,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,20:37:13,19.36,-155.10
3041,2018-05-03,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,04:32:33,19.45,-154.81
3053,2018-05-03,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,03:41:52,19.45,-154.88
3091,2018-05-02,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,23:35:16,19.44,-154.86
3252,2018-05-02,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,06:54:35,19.32,-154.92
3261,2018-05-02,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,05:41:24,19.45,-154.88
3277,2018-05-02,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,04:04:16,19.29,-155.08
3336,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,22:14:14,19.34,-154.97
3411,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,13:19:15,19.33,-154.98
3420,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 region de hawaii hawaii km utc sismo te...,12:44:54,19.36,-154.99
3447,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,09:48:35,19.39,-155.11
3470,2018-05-01,2.920049e+09,eq_map_es2,【 md 】 isla de hawaii hawaii km utc sismo terr...,08:06:44,19.38,-155.08
3477,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,07:42:42,19.39,-155.00
3496,2018-05-01,2.920049e+09,eq_map_es2,【 ml 】 isla de hawaii hawaii km utc sismo terr...,05:55:43,19.36,-155.05

## Removendo esses cabra

In [41]:
data = data[~ data['user_name'].str.contains("tmj")]
data = data[~ data['user_name'].str.contains("eq_map")]

### Quantos exemplos ainda sobraram no conjunto??

In [42]:
'Total: {}'.format(len(data))

'Total: 651'

### Exportando os dados

In [43]:
data.to_csv("DATASET_FINAL.csv",  index = None)